ADD overview.md
ReproNim/reprostim pull request #28
Opened 2021-07-14 20:18 UTC by andycon

2021-07-15 17:44 UTC, yarikoptic requested changes
Initial pass with some suggestions

2021-07-15 17:44 UTC, yarikoptic commented on overview.md
> +These raw recordings will often contain long periods of screen capture that show the content of the display on experimenter’s stimulus presentation computer (often a lab laptop).
I think we might want to make it even more explicit like:

```suggestion
These raw recordings will often contain long periods of screen capture that show the content of the display on experimenter’s stimulus presentation computer (often a lab laptop).  
**Warning: as a result, captured video could contain sensitive data if it was displayed.**
```

2021-09-02 15:55 UTC, yarikoptic commented on overview.md
> +[These details will be filled in later, and there is a reasonable sketch of the hardware set up already in the README.md file.]
will it be done in this PR or you would like to do that in a separate follow up PR?

2022-07-29 16:27 UTC, andycon commented
Yarick says to merge this here now.

2022-07-29 16:27 UTC, merged